### ISSUE TITLE
Disable debug messaging

### ISSUE THREAD

**Issue by ImpulseAdventure** [xlatb/ra8876#3]
Hi @xlatb -- thanks for putting this library together. I am evaluating adding support for your ra8876 controller library into [GUIslice](https://github.com/ImpulseAdventure/GUIslice).

I noticed that debug messaging is generated in a number of places throughout the code. Such messaging can certainly be helpful during initialization, though there are a couple functions that may be called upon frequently during user code execution (such as `selectExternalFont()` and `setTextScale()`). It would be great if we could either disable messaging in these two functions by default or, (ideally) provide a `#define` macro to enable/disable messages globally.

I will submit a pull request for such an enhancement in case you think it may be useful.

thanks

**Comment by xlatb** [comment]
Thank you. I merged your changes.
